logging:
  config: classpath:logs/logback-dev.xml
  file:
    path: ./logs

spring:
  flyway:
    enabled: false

  datasource:
    hikari:
      master:
        jdbcUrl: jdbc:mysql://mysql:3306/yeoboya_lunch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ENC(yLpEa4nqPnGRdvcM1rreaQ==)
        password: ENC(DNXfhwcMF0f35GnALXpmQg==)
        driverClassName: com.mysql.cj.jdbc.Driver
        poolName: kimzzang-db-master
      slave:
        jdbcUrl: jdbc:mysql://mysql:3306/yeoboya_lunch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ENC(/IM+NleJo976n0J00+S9xQ==)
        password: ENC(3ZK62S/0udpy2vw3FTycYQ==)
        driverClassName: com.mysql.cj.jdbc.Driver
        poolName: kimzzang-db-slave

  redis:
    host: redis
    port: 6379
    password: ENC(F+1DUxRZwTZUwQ2uJAg1aU2GdQuq7ZJ+)
    database: 0

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
        use_sql_comments: true
        generate_statistics: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: true

front:
  url: http://localhost:3001
