-- MEMBER + ROLE + PROVIDER
INSERT INTO member (member_id, login_id, email, name, password, provider, provider_id, role_roles_id, created_date,
                    last_modified_date)
VALUES (101, 'admin', 'admin@test.com', '관리자', '$2b$12$e.8T6TE/.Ax0Ob4g2TkUhO4y4WcI/zxiHgsIhuXOp/wHdUWGIbjLW',
        'yeoboya', '101', 1, NOW(), NOW()),
       (102, 'manager', 'manager@test.com', '매니저1', '$2b$12$e.8T6TE/.Ax0Ob4g2TkUhO4y4WcI/zxiHgsIhuXOp/wHdUWGIbjLW',
        'kakao', '102', 2, NOW(), NOW()),
       (103, 'user', 'user@test.com', '유저1', '$2b$12$e.8T6TE/.Ax0Ob4g2TkUhO4y4WcI/zxiHgsIhuXOp/wHdUWGIbjLW', 'naver',
        '103', 3, NOW(), NOW()),
       (104, 'guest01', 'guest01@test.com', '게스트1', 'guest_pass', 'google', '104', 4, NOW(), NOW()),
       (105, 'block01', 'block01@test.com', '차단1', 'block_pass', 'facebook', '105', 5, NOW(), NOW()),
       (106, 'user02', 'user02@test.com', '유저2', 'user_pass', 'google', '106', 3, NOW(), NOW()),
       (107, 'user03', 'user03@test.com', '유저3', 'user_pass', 'google', '107', 3, NOW(), NOW()),
       (108, 'user04', 'user04@test.com', '유저4', 'user_pass', 'google', '108', 3, NOW(), NOW()),
       (109, 'user05', 'user05@test.com', '유저5', 'user_pass', 'google', '109', 3, NOW(), NOW()),
       (110, 'guest02', 'guest02@test.com', '게스트2', 'guest_pass', 'github', '110', 4, NOW(), NOW());

-- USER_SECURITY_STATUS
INSERT INTO user_security_status (user_security_status_id, is_account_non_expired, is_account_non_locked,
                                  is_credentials_non_expired, is_enabled, member_id)
VALUES (201, true, true, true, true, 101),
       (202, true, true, true, true, 102),
       (203, true, true, true, true, 103),
       (204, true, true, true, true, 104),
       (205, true, false, true, true, 105), -- 차단 사용자
       (206, true, true, true, true, 106),
       (207, true, true, true, true, 107),
       (208, true, true, true, true, 108),
       (209, true, true, true, true, 109),
       (210, true, true, true, true, 110);

-- MEMBER_INFO
INSERT INTO member_info (member_info_id, bio, nick_name, phone_number, member_id)
VALUES (301, '관리자 소개', 'admin_nick1', '010-0000-0001', 101),
       (302, '매니저 소개', 'manager_nick1', '010-0000-0002', 102),
       (303, '유저 소개1', 'user_nick1', '010-0000-0003', 103),
       (304, '게스트 소개1', 'guest_nick1', '010-0000-0004', 104),
       (305, '차단 소개1', 'block_nick1', '010-0000-0005', 105),
       (306, '유저 소개2', 'user_nick2', '010-0000-0006', 106),
       (307, '유저 소개3', 'user_nick3', '010-0000-0007', 107),
       (308, '유저 소개4', 'user_nick4', '010-0000-0008', 108),
       (309, '유저 소개5', 'user_nick5', '010-0000-0009', 109),
       (310, '게스트 소개2', 'guest_nick2', '010-0000-0010', 110);

-- ACCOUNT (선택)
INSERT INTO account (account_id, account_number, bank_name, member_id, created_date, last_modified_date)
VALUES (401, '100-000-0001', '카카오뱅크', 101, NOW(), NOW()),
       (402, '100-000-0002', '신한은행', 102, NOW(), NOW()),
       (403, '100-000-0003', '국민은행', 103, NOW(), NOW()),
       (404, '100-000-0004', '우리은행', 104, NOW(), NOW()),
       (405, '100-000-0005', '하나은행', 105, NOW(), NOW());


-- BOARD_ID는 1000번부터 시작 (예시)
-- ABSTRACT_BOARD (공지사항 본문)
INSERT INTO ABSTRACT_BOARD (BOARD_ID, CREATED_BY, LAST_MODIFIED_BY, CONTENT, TITLE, BOARD_TYPE, CREATED_DATE,
                            LAST_MODIFIED_DATE, VIEW_COUNT)
VALUES (1000, 'admin', 'admin', '이번 주 식단표를 안내드립니다. 즐거운 점심 시간 되세요!', '3월 마지막 주 식단 안내', 'NOTICE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 12),
       (1001, 'admin', 'admin', '4월 1일부터 카페 운영 시간이 아래와 같이 변경됩니다. 참고 바랍니다.', '사내 카페 운영시간 변경 안내', 'NOTICE',
        DATEADD('DAY', -1, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP), 8),
       (1002, 'admin', 'admin', '오늘 15시부터 1시간 동안 사내 메신저 점검이 예정되어 있습니다.', '사내 메신저 서비스 점검 안내', 'NOTICE',
        DATEADD('DAY', -2, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP), 33),
       (1003, 'admin', 'admin', '신입사원 입문교육이 아래 일정으로 진행됩니다. 많은 참여 바랍니다.', '2025년 1차 신입사원 교육 일정', 'NOTICE',
        DATEADD('DAY', -3, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_TIMESTAMP), 14),
       (1004, 'admin', 'admin', '사내 정기 전산 점검이 진행될 예정입니다. 서비스 이용에 참고 부탁드립니다.', '전산 시스템 점검 공지', 'NOTICE',
        DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -4, CURRENT_TIMESTAMP), 22),
       (1005, 'admin', 'admin', '사내 보안 정책 강화를 위해 비밀번호 변경을 권고드립니다.', '보안 정책 변경 및 비밀번호 변경 요청', 'NOTICE',
        DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -5, CURRENT_TIMESTAMP), 17),
       (1006, 'admin', 'admin', '사내 임직원용 웰니스 프로그램 신청이 시작되었습니다.', '웰니스 프로그램 신청 안내', 'NOTICE',
        DATEADD('DAY', -6, CURRENT_TIMESTAMP), DATEADD('DAY', -6, CURRENT_TIMESTAMP), 25),
       (1007, 'admin', 'admin', '오늘은 여보야 점심 특별 메뉴가 제공됩니다. 놓치지 마세요!', '오늘의 특별 점심 메뉴 안내', 'NOTICE',
        DATEADD('DAY', -7, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_TIMESTAMP), 10),
       (1008, 'admin', 'admin', '이번 주 금요일 17시부터 서버 긴급 점검이 예정되어 있습니다.', '서버 긴급 점검 안내 (3/29)', 'NOTICE',
        DATEADD('DAY', -8, CURRENT_TIMESTAMP), DATEADD('DAY', -8, CURRENT_TIMESTAMP), 45),
       (1009, 'admin', 'admin', '임직원 여러분의 의견을 듣고자 설문을 진행합니다.', '사내 문화 개선 설문 참여 요청', 'NOTICE',
        DATEADD('DAY', -9, CURRENT_TIMESTAMP), DATEADD('DAY', -9, CURRENT_TIMESTAMP), 18),
       (1010, 'admin', 'admin', '근로자의 날 휴무 일정 및 급식 운영 여부를 안내드립니다.', '근로자의 날 휴무 안내', 'NOTICE',
        DATEADD('DAY', -10, CURRENT_TIMESTAMP), DATEADD('DAY', -10, CURRENT_TIMESTAMP), 21),
       (1011, 'admin', 'admin', '업데이트된 복지포인트 제도에 대해 안내드립니다.', '복지포인트 제도 개편 안내', 'NOTICE',
        DATEADD('DAY', -11, CURRENT_TIMESTAMP), DATEADD('DAY', -11, CURRENT_TIMESTAMP), 27),
       (1012, 'admin', 'admin', '사내 그룹웨어가 새로운 버전으로 업그레이드됩니다.', '그룹웨어 시스템 업데이트 공지', 'NOTICE',
        DATEADD('DAY', -12, CURRENT_TIMESTAMP), DATEADD('DAY', -12, CURRENT_TIMESTAMP), 36),
       (1013, 'admin', 'admin', '회의실 예약 시스템에 오류가 발생해 점검 중입니다.', '회의실 예약 시스템 점검 안내', 'NOTICE',
        DATEADD('DAY', -13, CURRENT_TIMESTAMP), DATEADD('DAY', -13, CURRENT_TIMESTAMP), 15),
       (1014, 'admin', 'admin', '업무에 참고할 수 있는 여름 휴가 가이드라인을 공유드립니다.', '2025 여름 휴가 가이드 배포', 'NOTICE',
        DATEADD('DAY', -14, CURRENT_TIMESTAMP), DATEADD('DAY', -14, CURRENT_TIMESTAMP), 40),
       (1015, 'admin', 'admin', '이번 분기 인사이동 내역을 공유드립니다.', '2025년 2분기 인사이동 공지', 'NOTICE',
        DATEADD('DAY', -15, CURRENT_TIMESTAMP), DATEADD('DAY', -15, CURRENT_TIMESTAMP), 11),
       (1016, 'admin', 'admin', '전 사원 대상 긴급 공지입니다. 오늘 18시 전까지 확인 바랍니다.', '전사 긴급공지: 업무자료 제출 마감', 'NOTICE',
        DATEADD('DAY', -16, CURRENT_TIMESTAMP), DATEADD('DAY', -16, CURRENT_TIMESTAMP), 13),
       (1017, 'admin', 'admin', '이번 주 금요일, 사내 네트워크가 일시 중단됩니다.', '사내 네트워크 일시 중단 안내', 'NOTICE',
        DATEADD('DAY', -17, CURRENT_TIMESTAMP), DATEADD('DAY', -17, CURRENT_TIMESTAMP), 8),
       (1018, 'admin', 'admin', '팀원 간 협업 강화를 위한 워크숍이 열립니다.', '협업 워크숍 개최 안내', 'NOTICE',
        DATEADD('DAY', -18, CURRENT_TIMESTAMP), DATEADD('DAY', -18, CURRENT_TIMESTAMP), 6),
       (1019, 'admin', 'admin', '회의실 무단 사용 관련 주의 공지입니다.', '회의실 무단 사용 자제 요청', 'NOTICE',
        DATEADD('DAY', -19, CURRENT_TIMESTAMP), DATEADD('DAY', -19, CURRENT_TIMESTAMP), 9);

-- NOTICE (공지사항 메타데이터)
INSERT INTO NOTICE (ATTACHMENT_URL, AUTHOR, CATEGORY, START_DATE, END_DATE, PINNED, STATUS, BOARD_ID)
VALUES ('https://example.com/notice1', 'admin', '식단', CURRENT_DATE, DATEADD('DAY', 3, CURRENT_DATE), 0, 'ACTIVE', 1000),
       ('https://example.com/notice2', 'admin', '운영', CURRENT_DATE, DATEADD('DAY', 7, CURRENT_DATE), 0, 'ACTIVE', 1001),
       ('https://example.com/notice3', 'admin', '점검', DATEADD('DAY', -1, CURRENT_DATE), DATEADD('DAY', 1, CURRENT_DATE),
        1, 'ACTIVE', 1002),
       ('https://example.com/notice4', 'admin', '교육', CURRENT_DATE, DATEADD('DAY', 30, CURRENT_DATE), 0, 'ACTIVE',
        1003),
       ('https://example.com/notice5', 'admin', '점검', DATEADD('DAY', -10, CURRENT_DATE),
        DATEADD('DAY', -5, CURRENT_DATE), 0, 'INACTIVE', 1004),
       ('https://example.com/notice6', 'admin', '보안', CURRENT_DATE, DATEADD('DAY', 14, CURRENT_DATE), 0, 'ACTIVE',
        1005),
       ('https://example.com/notice7', 'admin', '복지', CURRENT_DATE, DATEADD('MONTH', 1, CURRENT_DATE), 0, 'ACTIVE',
        1006),
       ('https://example.com/notice8', 'admin', '식단', CURRENT_DATE, DATEADD('DAY', 1, CURRENT_DATE), 0, 'ACTIVE', 1007),
       ('https://example.com/notice9', 'admin', '점검', DATEADD('DAY', -1, CURRENT_DATE), CURRENT_DATE, 1, 'ACTIVE',
        1008),
       ('https://example.com/notice10', 'admin', '설문', CURRENT_DATE, DATEADD('DAY', 3, CURRENT_DATE), 0, 'ACTIVE',
        1009),
       ('https://example.com/notice11', 'admin', '휴무', CURRENT_DATE, DATE '2025-05-01', 0, 'ACTIVE', 1010),
       ('https://example.com/notice12', 'admin', '복지', CURRENT_DATE, DATEADD('DAY', 14, CURRENT_DATE), 0, 'ACTIVE',
        1011),
       ('https://example.com/notice13', 'admin', '시스템', CURRENT_DATE, DATEADD('DAY', 7, CURRENT_DATE), 0, 'ACTIVE',
        1012),
       ('https://example.com/notice14', 'admin', '점검', DATEADD('DAY', -5, CURRENT_DATE),
        DATEADD('DAY', -1, CURRENT_DATE), 0, 'INACTIVE', 1013),
       ('https://example.com/notice15', 'admin', '가이드', CURRENT_DATE, DATE '2025-08-31', 0, 'ACTIVE', 1014),
       ('https://example.com/notice16', 'admin', '인사', CURRENT_DATE, DATEADD('DAY', 7, CURRENT_DATE), 0, 'ACTIVE',
        1015),
       ('https://example.com/notice17', 'admin', '긴급', CURRENT_DATE, DATEADD('DAY', 1, CURRENT_DATE), 1, 'ACTIVE',
        1016),
       ('https://example.com/notice18', 'admin', '점검', DATEADD('DAY', -1, CURRENT_DATE),
        DATEADD('DAY', 1, CURRENT_DATE), 0, 'ACTIVE', 1017),
       ('https://example.com/notice19', 'admin', '행사', CURRENT_DATE, DATEADD('DAY', 3, CURRENT_DATE), 0, 'ACTIVE',
        1018),
       ('https://example.com/notice20', 'admin', '주의', CURRENT_DATE, DATEADD('DAY', 365, CURRENT_DATE), 0, 'ACTIVE',
        1019);

INSERT INTO ABSTRACT_BOARD (BOARD_ID, CREATED_BY, LAST_MODIFIED_BY, CONTENT, TITLE, BOARD_TYPE, CREATED_DATE,
                            LAST_MODIFIED_DATE, VIEW_COUNT)
VALUES (2000, 'user', 'user', '최근 다이어트를 시작했는데, 회사 밥이 너무 맛있어서 힘들어요.', '식단과 다이어트 조절이 너무 힘드네요', 'FREE', NOW(), NOW(), 34),
       (2001, 'user02', 'user02', '이 영화 완전 강추! 반전도 있고 감동도 있어요.', '이번 주말에 본 영화 후기', 'FREE', NOW(), NOW(), 28),
       (2002, 'user03', 'user03', '이번 주말에 양평으로 드라이브 갔다 왔어요. 풍경이 끝내줌!', '양평 드라이브 후기 (사진 있음)', 'FREE', NOW(), NOW(), 51),
       (2003, 'user04', 'user04', '회의 일정 변경 관련해서 혼선이 생겨서 다시 공유드립니다.', '금요일 회의 시간 변경', 'FREE', NOW(), NOW(), 13),
       (2004, 'user05', 'user05', '점심시간에 팀원들과 탁구 치는 재미가 쏠쏠하네요.', '요즘 점심시간 탁구에 빠졌어요', 'FREE', NOW(), NOW(), 21),
       (2005, 'manager', 'manager', '다음 주부터는 실내 마스크가 자유화됩니다. 참고 부탁드려요.', '실내 마스크 착용 관련 공지', 'FREE', NOW(), NOW(), 40),
       (2006, 'user02', 'user02', '피카츄 젤리 요즘 인기라는데, CU에 있더라고요.', '피카츄 젤리 먹어보신 분?', 'FREE', NOW(), NOW(), 11),
       (2007, 'admin', 'admin', '요즘 유튜브에서 스터디윗미 영상 보고 같이 공부하는 중이에요.', '스터디윗미 영상 추천 좀 해주세요!', 'FREE', NOW(), NOW(), 18),
       (2008, 'guest01', 'guest01', '넷플릭스 신작 중에 볼만한 거 있을까요?', '넷플 신작 뭐 보세요?', 'FREE', NOW(), NOW(), 25),
       (2009, 'user03', 'user03', '우리 회사 냥이들 사진 공유해요~', '사무실 고양이 사진 모음.zip', 'FREE', NOW(), NOW(), 33),
       (2010, 'user05', 'user05', '개인 업무 능률 올리는 팁 공유해요.', '집중 잘 되는 나만의 루틴', 'FREE', NOW(), NOW(), 12),
       (2011, 'manager', 'manager', '식기세척기 고장났대요. 점심 이후 수저 챙기세요.', '사내 식기세척기 점검 공지', 'FREE', NOW(), NOW(), 17),
       (2012, 'guest02', 'guest02', '요즘 AI 공부하는데 좋은 유튜브 채널 없을까요?', 'AI 독학 추천 채널', 'FREE', NOW(), NOW(), 29),
       (2013, 'user', 'user', '사무실 책상에 작은 화분 놓았는데 힐링되네요~', '작은 화분 하나의 힘', 'FREE', NOW(), NOW(), 19),
       (2014, 'user04', 'user04', '오늘 점심 메뉴 치킨이라던데 사실인가요?', '점심 치킨 루머 실화?', 'FREE', NOW(), NOW(), 41),
       (2015, 'admin', 'admin', '다음 분기부터 교육 프로그램이 바뀐다고 하네요.', '분기별 교육 내용 변경 안내', 'FREE', NOW(), NOW(), 22),
       (2016, 'user02', 'user02', '최근에 시작한 웹툰 추천 좀 해주세요!', '웹툰 뭐 보시나요?', 'FREE', NOW(), NOW(), 30),
       (2017, 'user03', 'user03', '노션 템플릿 공유해요~ 업무 효율에 도움돼요.', '노션 템플릿 공유 (업무용)', 'FREE', NOW(), NOW(), 27),
       (2018, 'user04', 'user04', '편의점 신상 간식 추천해요. 진짜 맛있어요.', '요즘 핫한 편의점 간식들', 'FREE', NOW(), NOW(), 35),
       (2019, 'user05', 'user05', '디자인팀에서 배운 Figma 꿀팁 공유합니다!', 'Figma 꿀팁 모음.zip', 'FREE', NOW(), NOW(), 23),
       (2020, 'manager', 'manager', '카카오워크 상태 설정 어떻게 하시나요?', '카카오워크 상태메시지 공유해봐요', 'FREE', NOW(), NOW(), 15),
       (2021, 'user', 'user', '오늘 커피머신에 필터가 없었어요ㅠㅠ', '커피머신 관리 좀 부탁드립니다', 'FREE', NOW(), NOW(), 20),
       (2022, 'user03', 'user03', '출근길에 들은 팟캐스트 추천합니다.', '출근길 추천 팟캐스트 🎧', 'FREE', NOW(), NOW(), 14),
       (2023, 'user04', 'user04', '업무용 키보드 어떤 거 쓰세요?', '기계식 키보드 vs 멤브레인', 'FREE', NOW(), NOW(), 26),
       (2024, 'user02', 'user02', '화요일 점심 메뉴에 오므라이스 있대요!', '점심 오므라이스 확인 완료 ✅', 'FREE', NOW(), NOW(), 9),
       (2025, 'admin', 'admin', '내일 회식 메뉴 투표합시다~', '회식 메뉴 뭐 먹을까요?', 'FREE', NOW(), NOW(), 32),
       (2026, 'user03', 'user03', '비 오는 날 듣기 좋은 노래 추천해주세요~', '비 오는 날 감성 플레이리스트', 'FREE', NOW(), NOW(), 24),
       (2027, 'user04', 'user04', '주말에 동물농장 갔다왔는데 힐링 그 자체...', '동물농장 체험 후기 🐷', 'FREE', NOW(), NOW(), 31),
       (2028, 'user', 'user', '시간관리 앱 뭐 쓰세요?', '타임블로킹에 도움 되는 앱 추천', 'FREE', NOW(), NOW(), 16),
       (2029, 'guest02', 'guest02', '포트폴리오 정리 중인데 팁 있으신 분?', '개발자 포폴 꿀팁 공유해요!', 'FREE', NOW(), NOW(), 38);

INSERT INTO FREE_BOARD (BOARD_ID, MEMBER_ID, CATEGORY, PIN, SECRET)
VALUES (2000, 103, '일상', 0, FALSE),
       (2001, 106, '문화', 0, FALSE),
       (2002, 107, '여행', 0, FALSE),
       (2003, 108, '업무', 0, FALSE),
       (2004, 109, '취미', 0, FALSE),
       (2005, 102, '공지', 0, FALSE),
       (2006, 106, '식품', 0, FALSE),
       (2007, 101, '공부', 0, FALSE),
       (2008, 104, '문화', 0, FALSE),
       (2009, 107, '사진', 0, FALSE),
       (2010, 109, '노하우', 0, FALSE),
       (2011, 102, '공지', 0, FALSE),
       (2012, 110, 'IT', 0, FALSE),
       (2013, 103, '라이프', 0, FALSE),
       (2014, 108, '식품', 0, FALSE),
       (2015, 101, '교육', 0, FALSE),
       (2016, 106, '문화', 0, FALSE),
       (2017, 107, '생산성', 0, FALSE),
       (2018, 108, '식품', 0, FALSE),
       (2019, 109, '디자인', 0, FALSE),
       (2020, 102, 'IT', 0, FALSE),
       (2021, 103, '불편사항', 0, FALSE),
       (2022, 107, '추천', 0, FALSE),
       (2023, 108, '장비', 0, FALSE),
       (2024, 106, '식단', 0, FALSE),
       (2025, 101, '이벤트', 0, FALSE),
       (2026, 107, '음악', 0, FALSE),
       (2027, 108, '여행', 0, FALSE),
       (2028, 103, '앱', 0, FALSE),
       (2029, 110, '개발', 0, FALSE);
