insert into ROLE_HIERARCHY (ROLE_HIERARCHY_ID, CHILD_NAME, PARENT_NAME)
values (6,'ROLE_WITHDRAWN','ROLE_BLOCK');

insert into PUBLIC.ROLE (ROLES_ID, ROLE, ROLE_DESC)
values (6,'ROLE_WITHDRAWN','탈퇴');