-- V5: 공지사항 테이블 수정 - TIMESTAMP → DATE, PRIORITY 제거, PINNED 추가

ALTER TABLE NOTICE DROP COLUMN PRIORITY;

ALTER TABLE NOTICE ADD COLUMN PINNED TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE NOTICE
    MODIFY START_DATE DATE,
    MODIFY END_DATE DATE;